{
 "title": "fluent-bit to Splunk metrics",
 "time": { "from": "2018-09-25T21:17:12.011Z", "to": "2018-09-25T21:27:12.011Z" },
 "panels": [
  { "title": "fluent-bit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "I/O totals",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "- sum by (name) (rate(fluentbit_input_records_total[5m]))"
    },
    {
     "expr": "sum by (name) (rate(fluentbit_output_proc_records_total[5m]))"
    }
   ]
  },
  {
   "title": "Total queue (all input - http output)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total{name=~\".+\"}[2m])) - sum(rate(fluentbit_output_proc_records_total{name=~\"http.+\"}[2m]))"
    }
   ]
  },
  {
   "title": "Active integrations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(irate(fluentbit_output_proc_records_total{name=~\"http.+\"}[2m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Input rate by instance (relative, %)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(fluentbit_input_records_total[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heartbeats",
   "type": "graph",
   "description": "fluent-bit heartbeats are backpressure-sensitive",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(fluentbit_input_records_total{name=~\"dummy.+\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Splunk UF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Splunk to Splunk upstream connection rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(splunk_tcpout_connections_established_total[2m])",
     "legendFormat": "New connection rate"
    },
    {
     "expr": "max_over_time(splunk_tcpout_connections_failed_total[2m]) ",
     "legendFormat": "Connections failed rate"
    },
    {
     "expr": "max_over_time(splunk_tcpout_connections_refused_total[2m])",
     "legendFormat": "Connections refused rate"
    }
   ]
  },
  {
   "title": "Splunk to Splunk upstream throughput eps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(splunk_thruput_cooked_output_events_total[2m])"
    }
   ]
  },
  {
   "title": "HEC input - Average bytes/event",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(splunk_hec_total_bytes_indexed[2m]) / rate(splunk_hec_num_of_events[2m]))",
     "legendFormat": "rate bytes/event"
    },
    {
     "expr": "(stddev_over_time(splunk_hec_total_bytes_indexed[2m]) / stddev_over_time(splunk_hec_num_of_events[2m]))",
     "legendFormat": "stddev bytes/event"
    }
   ]
  },
  {
   "title": "HEC input - Open requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "splunk_hec_num_of_requests_all" },
    {}
   ]
  },
  {
   "title": "HEC Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(splunk_hec_num_of_errors[2m])",
     "legendFormat": "HEC errors"
    },
    {
     "expr": "rate(splunk_hec_num_of_parser_errors[2m])",
     "legendFormat": "HEC parser errors"
    },
    {
     "expr": "rate(splunk_hec_num_of_auth_failures[2m])",
     "legendFormat": "HEC auth failures"
    }
   ]
  }
 ]
}